gst-openmax: remove obsolete patch
Task `configure` fails with the following error with `angstrom-2008.1` and `MACHINE = "beagleboard"`.

	| configure: using GStreamer tools in /usr/bin
	| configure: using GStreamer plug-ins in /usr/lib/gstreamer-0.10
	| checking for GST_BASE... yes
	| checking for GST_CHECK... no
	| no
	| configure: No package 'gstreamer-check' found
	| configure: error: no gstreamer-check >= 0.10.0 (GStreamer Check unittest Library) found
	| ERROR: Function do_configure failed
	NOTE: package gst-openmax-0.10.0.4-r0: task do_configure: Failed
	ERROR: TaskFailed event exception, aborting
	ERROR: Build of /oe/openembedded/recipes/openmax/gst-openmax_0.10.0.4.bb do_configure failed
	ERROR: Task 11 (/oe/openembedded/recipes/openmax/gst-openmax_0.10.0.4.bb, do_configure) failed with 256

With current GStreamer `gstreamer-0.10.31-r2` this patch is not necessary anymore and removing it fixes the build. When the recipe was committed with the patch in 1eef6ac1 [1] GStreamer 0.10.17 was used [2].

[1] http://cgit.openembedded.org/cgit.cgi/openembedded/commit/?id=1eef6ac18de15ea845b146b1624fcc1f1c4faea2
[2] http://cgit.openembedded.org/cgit.cgi/openembedded/commit/?id=3422a436880509c7f82a3ae5d5693c87ece7a42d

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
Acked-by: Koen Kooi <koen@openembedded.org>
Signed-off-by: Khem Raj <raj.khem@gmail.com>