libomxil-bellagio: remove/delete unused versions 0.9.{0, 1, 2}
These version are not used anymore and 0.9.{0,1} do not even build with current FFmpeg [1].

	$ zless minimal-dev/work/armv7a-oe-linux-gnueabi/libomxil-bellagio-0.9.0-r8.0/temp/log.do_compile.16833
	[…]
	/bin/sh ../../../arm-oe-linux-gnueabi-libtool  --tag=CC   --mode=compile arm-oe-linux-gnueabi-gcc -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -m
	no-thumb -DHAVE_CONFIG_H -I. -I../../..   -isystem/oe/build-minimal-eglibc/minimal-dev/sysroots/armv7a-oe-linux-gnueabi/usr/include -I/oe/build-minimal-eglibc/m
	inimal-dev/sysroots/armv7a-oe-linux-gnueabi/usr//include   -I../../../include -I../../../src -I../../../src/base -isystem/oe/build-minimal-eglibc/minimal-dev/sysroots/arm
	v7a-oe-linux-gnueabi/usr/include -fexpensive-optimizations -fomit-frame-pointer -frename-registers -Os -pthread -g -Wall -MT libomxffmpeg_la-omx_ffmpeg_colorconv_component.lo -MD -
	MP -MF .deps/libomxffmpeg_la-omx_ffmpeg_colorconv_component.Tpo -c -o libomxffmpeg_la-omx_ffmpeg_colorconv_component.lo `test -f 'omx_ffmpeg_colorconv_component.c' || echo './'`omx
	_ffmpeg_colorconv_component.c
	arm-oe-linux-gnueabi-libtool: compile:  arm-oe-linux-gnueabi-gcc -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -mno-thumb -DHAVE_CONFIG_H -I. -I..
	/../.. -isystem/oe/build-minimal-eglibc/minimal-dev/sysroots/armv7a-oe-linux-gnueabi/usr/include -I/oe/build-minimal-eglibc/minimal-dev/sysroots/armv7a-oe-linux
	-gnueabi/usr//include -I../../../include -I../../../src -I../../../src/base -isystem/oe/build-minimal-eglibc/minimal-dev/sysroots/armv7a-oe-linux-gnueabi/usr/include -fex
	pensive-optimizations -fomit-frame-pointer -frename-registers -Os -pthread -g -Wall -MT libomxffmpeg_la-omx_ffmpeg_colorconv_component.lo -MD -MP -MF .deps/libomxffmpeg_la-omx_ffmp
	eg_colorconv_component.Tpo -c omx_ffmpeg_colorconv_component.c  -fPIC -DPIC -o .libs/libomxffmpeg_la-omx_ffmpeg_colorconv_component.o
	omx_ffmpeg_colorconv_component.c: In function 'find_ffmpeg_pxlfmt':
	omx_ffmpeg_colorconv_component.c:72:23: error: 'PIX_FMT_RGBA32' undeclared (first use in this function)
	omx_ffmpeg_colorconv_component.c:72:23: note: each undeclared identifier is reported only once for each function it appears in
	omx_ffmpeg_colorconv_component.c: In function 'omx_ffmpeg_colorconv_component_BufferMgmtCallback':
	omx_ffmpeg_colorconv_component.c:799:13: warning: passing argument 2 of 'sws_scale' from incompatible pointer type
	/oe/build-minimal-eglibc/minimal-dev/sysroots/armv7a-oe-linux-gnueabi/usr/include/libswscale/swscale.h:195:5: note: expected 'const uint8_t * const*' but argument is of type 'uint8_t **'
	make[4]: *** [libomxffmpeg_la-omx_ffmpeg_colorconv_component.lo] Error 1
	make[4]: Leaving directory `/oe/build-minimal-eglibc/minimal-dev/work/armv7a-oe-linux-gnueabi/libomxil-bellagio-0.9.0-r8.0/libomxil-bellagio-0.9.0/src/components/ffmpeg'
	make[3]: *** [all-recursive] Error 1
	make[3]: Leaving directory `/oe/build-minimal-eglibc/minimal-dev/work/armv7a-oe-linux-gnueabi/libomxil-bellagio-0.9.0-r8.0/libomxil-bellagio-0.9.0/src/components'
	make[2]: *** [all-recursive] Error 1
	make[2]: Leaving directory `/oe/build-minimal-eglibc/minimal-dev/work/armv7a-oe-linux-gnueabi/libomxil-bellagio-0.9.0-r8.0/libomxil-bellagio-0.9.0/src'
	make[1]: *** [all-recursive] Error 1
	make[1]: Leaving directory `/oe/build-minimal-eglibc/minimal-dev/work/armv7a-oe-linux-gnueabi/libomxil-bellagio-0.9.0-r8.0/libomxil-bellagio-0.9.0'
	make: *** [all] Error 2
	FATAL: oe_runmake failed
	ERROR: Function do_compile failed

0.9.2 probably would build with a similar as [2]. Furthermore 0.9.2.1 has been around for over a year (77195e32 [2]).

[1] http://lists.linuxtogo.org/pipermail/openembedded-devel/2011-January/028804.html
[2] http://patches.openembedded.org/patch/315/
[3] http://cgit.openembedded.org/cgit.cgi/openembedded/commit/?id=77195e32400dd86facc038f61190139d38f14b31

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
Acked-by: Koen Kooi <koen@openembedded.org>
Signed-off-by: Khem Raj <raj.khem@gmail.com>